vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        logos:
            uri_prefix: /uploads/logos
            upload_destination: '%kernel.project_dir%/public/uploads/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        typeetablissement:
            uri_prefix: /uploads/typeetablissement
            upload_destination: '%kernel.project_dir%/public/uploads/typeetablissement'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer